#!/usr/bin/env bash

# {{{ Ubuntu utilities

<%= import 'shell-scripts/ubuntu.sh' %>
<%= import 'shell-scripts/ubuntu-extras.sh' %>
<%= import 'shell-scripts/ubuntu-postgres.sh' %>

# }}}

# {{{ Configuration

vagrant_user='vagrant'

project_path="/${vagrant_user}"

# {{{ PHP

composer_binary="${project_path}/bin/composer.phar"

# }}}

# }}}

# {{{ DNS

# Use Google Public DNS for resolving domain names.
# The default is host-only DNS which may not be installed.
nameservers-local-purge
nameservers-append '8.8.8.8'
nameservers-append '8.8.4.4'

# }}}

# {{{ Aptitute/Packages

# {{{ PHP

apt-packages-ppa 'ondrej/php5'

# }}}

# {{{ Nginx

apt-packages-ppa 'nginx/stable'

# }}}

# Use a local Ubuntu mirror, results in faster downloads.
apt-mirror-pick 'uk'

# Update packages cache.
apt-packages-update

# }}}

# {{{ Prerequisites

# Install at least one Ubuntu locale.
apt-packages-install language-pack-en

# Git is required by Composer to install packages from source.
apt-packages-install git-core

# }}}

# {{{ PHP

# cURL is required by 'guzzle/guzzle'.
apt-packages-install php5-cli php5-fpm php5-curl

# {{{ Settings

php-settings-update 'date.timezone' 'Europe/London'
php-settings-update 'display_errors' 'On'

# }}}

# {{{ Composer

# Install (or update) Composer locally to project bin/
log-operation 'php' 'install' 'composer.phar'
if [ -f "$composer_binary" ]; then
  php "$composer_binary" self-update
else
  package-uri-download 'https://getcomposer.org/installer' | php -- --install-dir="$( dirname "$composer_binary" )"
fi

# Install Composer/PHP dependencies.
log-operation 'php' 'install' 'composer.json'
( cd "$project_path" && COMPOSER_PROCESS_TIMEOUT=3600 php "$composer_binary" install --dev --prefer-source )

# }}}

# }}}

# {{{ Nginx

apt-packages-install nginx

# Replace the default Nginx site.
EXTRA="$( cat <<'EOD'
<%= import 'extra/etc/nginx/sites-available/vagrant.fragment' %>
EOD
)" \
PHP="$( which php5-fpm )" \
nginx-sites-create "$vagrant_user" "${project_path}/src"

nginx-sites-disable 'default'
nginx-sites-enable "$vagrant_user"

# }}}

# {{{ Restarting Services

php-fpm-restart
nginx-restart

# }}}
